Platform golden container instance (and capacity provider refactor)
DaySmart/daysmart-cdk-constructs pull request #18
Opened 2021-06-15 00:22 UTC by MarteagaJ

2021-06-15 14:43 UTC, traviswalker26 commented
These policies are super specific to our company so I don't think we should have them in this repo. Let's move them out of here and make the policies a parameter of these constructs.

2021-06-15 14:48 UTC, traviswalker26 requested changes
The IAM roles are too specific to our company to open source. We should move them to our internal repositories and make them parameters of this construct.

2021-06-17 12:10 UTC, traviswalker26 approved these changes

2021-06-17 12:20 UTC, chrisdettloff approved these changes
LGTM!

2021-06-17 13:19 UTC, merged