Alert on Cloudfront Invalidation but Still Pass
DaySmart/daysmart-cdk-constructs pull request #20
Opened 2021-06-29 21:43 UTC by MarteagaJ

2021-06-30 13:06 UTC, traviswalker26 requested changes

2021-06-30 13:06 UTC, traviswalker26 commented on packages/cdk-s3-deployment/lib/lambda/handler.py
> +    lambda_client.invoke(FunctionName='serverless-slack-chatops-dev-sendSlack',
I'd rather we not invoke the function directly. I think this should publish to an SNS topic that way we can direct the message in multiple ways if we wanted. Also we don't want to hardcode function resource names.

2021-07-02 12:40 UTC, traviswalker26 approved these changes

2021-07-02 13:16 UTC, chrisdettloff approved these changes

2021-07-06 13:22 UTC, merged