Atlas 2787
DaySmart/daysmart-cdk-constructs pull request #68
Opened 2022-03-11 17:49 UTC by BennuAshes

2022-03-14 19:31 UTC, nthornton2010 requested changes

2022-03-15 19:33 UTC, BennuAshes commented on packages/cdk-routing-split/package.json
> +        "test:watchsandbox": "sls export-env --stage sandbox --aws-profile sandbox && jest --watch",
i think ill just get rid of it, i ended up not using it that much. i think your suggestion of -- --watch is good

2022-03-15 19:40 UTC, BennuAshes commented on packages/cdk-routing-split/src/get-origin/handler.ts
> +        console.log('jest-', subdomain, domain, pathname, queryStrings);
i don't see this anymore, im fairly certain i removed it as part of the update lambda (that got merged last night)

2022-03-15 19:42 UTC, BennuAshes commented on packages/cdk-routing-split/test/cases/unit/get-origin.test.ts
> +    it('calls get-origin with no domainName', async () => {
ill change it, its bugging me now that you pointed it out

2022-03-15 19:50 UTC, BennuAshes commented on packages/cdk-routing-split/test/cases/integration/get-origin.test.ts
> +    it('calls get-origin with a valid url with a subdomain', async () => {
Ah yea great idea, adding it now.

2022-03-16 14:47 UTC, nthornton2010 requested changes

2022-03-16 14:47 UTC, nthornton2010 commented on packages/cdk-routing-split/test/cases/integration/get-origin.test.ts
> +        const origin = pathRequest.origin;
This should be domain request. The lowest number has the highest priority, so the domainRequest's origin is what should be expected.

2022-03-16 14:47 UTC, nthornton2010 commented on packages/cdk-routing-split/test/setup/jest.setup.js
> +    //log: jest.fn(),
This shouldn't have been committed.

2022-03-16 14:47 UTC, nthornton2010 commented on packages/cdk-routing-split/test/steps/when.ts
> +    console.log('add - body', body);
A new console.log was added. Please make sure you're code reviewing your changes before committing them.

2022-03-16 14:51 UTC, nthornton2010 commented on packages/cdk-routing-split/test/steps/when.ts
> +    console.log('add - body', body);
Oh, this is a test file, sorry my mistake.

2022-03-16 15:50 UTC, merged